#http
services:
  app:
    image: ghcr.io/mahn-ke/slides-by-vincent:latest@sha256:c38ac56d75ea991479b5b010307899f3eee9a8652569d51289d1aa651b802b3e
    restart: on-failure:5
    environment:
      - PORT=3000
    ports:
      - "3009:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 5
