#http
services:
  app:
    image: ghcr.io/mahn-ke/slides-by-vincent:latest@sha256:378108e5a47808142cca33192db7e05bb2945c38fec91e6b991a4eee66c4daa2
    restart: on-failure:5
    environment:
      - PORT=3000
    ports:
      - "3009:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 5
