#http
services:
  app:
    image: ghcr.io/mahn-ke/slides-by-vincent:latest@sha256:96f34a1755af58d738810261f9e1ac6df0229f4e3cd528adc8ca59fd8640c828
    restart: on-failure:5
    environment:
      - PORT=3000
    ports:
      - "3009:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 5
